version: "3.8"

services:
  db-mysql:
    image: mysql:5.7
    container_name: mysql5_7
    restart: always
    privileged: true
    volumes:
      # files
      - ./files/:/var/lib/mysql-files/
     # data
      - ./data/:/var/lib/mysql/
    environment:
      TZ : Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 4Kmidn49qeXSUO5k
      MYSQL_DATABASE: jimo-form
    ports:
      - 13306:3306
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    networks:
      - internal
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=4Kmidn49qeXSUO5k --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  service-app:
    image: ccr.ccs.tencentyun.com/xiaohuodui/jimo-form-app:v1.0.7_1
    container_name: jimo-form-app
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://db-mysql:3306/jimo-form?useSSL=false&autoReconnect=true&characterEncoding=utf8",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "4Kmidn49qeXSUO5k",
            "buddy.config": "/buddy/config.prod.json"
          }'
    depends_on:
        db-mysql:
           condition: "service_healthy"
    ports:
      - 9000:9000
    networks:
      - internal
networks:
  internal:
    name: internal